<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBQI8H45\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBQI8H45/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBQI8H45.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBQI8H45\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBQI8H45\App_KernelDevDebugContainer([
    'container.build_hash' => 'BQI8H45',
    'container.build_id' => '64d5d260',
    'container.build_time' => 1615543130,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBQI8H45');
