<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG2JitaT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG2JitaT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG2JitaT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG2JitaT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG2JitaT\App_KernelDevDebugContainer([
    'container.build_hash' => 'G2JitaT',
    'container.build_id' => '14df7425',
    'container.build_time' => 1612280664,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG2JitaT');
